import { Spot } from "./types";

/**
 * MVPデモ用のダミースポットデータ（渋谷〜恵比寿〜代官山エリア）。
 * 実店舗名ではなく仮称。Google Places API 連携後はこのモジュールを置き換える。
 */
export const MOCK_SPOTS: Spot[] = [
  {
    id: "spot-01",
    name: "代々木しずくの森公園",
    category: "公園",
    moods: ["mattari", "photo"],
    lat: 35.6716,
    lng: 139.6949,
    stayMinutes: 40,
    priceLevel: 0,
    description: "緑に囲まれた散策路と池がある都市公園。",
  },
  {
    id: "spot-02",
    name: "ヒカリ焙煎珈琲 渋谷店",
    category: "カフェ",
    moods: ["mattari", "gourmet"],
    lat: 35.659,
    lng: 139.7016,
    stayMinutes: 35,
    priceLevel: 1,
    description: "自家焙煎豆と焼き菓子が人気の隠れ家カフェ。",
  },
  {
    id: "spot-03",
    name: "恵比寿レンガテラス市場",
    category: "商業施設",
    moods: ["gourmet", "active"],
    lat: 35.6467,
    lng: 139.71,
    stayMinutes: 50,
    priceLevel: 2,
    description: "食べ歩きグルメが並ぶレンガ造りの屋台街。",
  },
  {
    id: "spot-04",
    name: "代官山ミラーウォール",
    category: "フォトスポット",
    moods: ["photo", "active"],
    lat: 35.6494,
    lng: 139.7031,
    stayMinutes: 20,
    priceLevel: 0,
    description: "鏡張りの壁面アートが撮影スポットとして人気。",
  },
  {
    id: "spot-05",
    name: "渋谷スカイラウンジ展望テラス",
    category: "展望施設",
    moods: ["photo", "active"],
    lat: 35.6586,
    lng: 139.7016,
    stayMinutes: 45,
    priceLevel: 3,
    description: "高層階から街並みを一望できる展望テラス。",
  },
  {
    id: "spot-06",
    name: "青葉湯どころ",
    category: "銭湯・温浴",
    moods: ["mattari"],
    lat: 35.6553,
    lng: 139.6944,
    stayMinutes: 60,
    priceLevel: 1,
    description: "レトロな造りの日帰り湯どころ。サウナ併設。",
  },
  {
    id: "spot-07",
    name: "だし香る おでん横丁",
    category: "居酒屋",
    moods: ["gourmet"],
    lat: 35.6604,
    lng: 139.6989,
    stayMinutes: 55,
    priceLevel: 2,
    description: "出汁の効いたおでんと日本酒が楽しめる横丁の一角。",
  },
  {
    id: "spot-08",
    name: "文化雑貨アトリエ SORA",
    category: "雑貨・ギャラリー",
    moods: ["photo", "mattari"],
    lat: 35.6478,
    lng: 139.6978,
    stayMinutes: 30,
    priceLevel: 1,
    description: "作家ものの器や雑貨を扱う小さなギャラリーショップ。",
  },
  {
    id: "spot-09",
    name: "神南すし工房",
    category: "寿司",
    moods: ["gourmet"],
    lat: 35.6633,
    lng: 139.6997,
    stayMinutes: 60,
    priceLevel: 3,
    description: "立ち食いスタイルでにぎり寿司を気軽に楽しめる店。",
  },
  {
    id: "spot-10",
    name: "南平台クライミングベース",
    category: "アクティビティ",
    moods: ["active"],
    lat: 35.655,
    lng: 139.6969,
    stayMinutes: 70,
    priceLevel: 2,
    description: "初心者向けボルダリング体験ができるスポーツ施設。",
  },
  {
    id: "spot-11",
    name: "旧山手線ガード下ストリート",
    category: "ストリートアート",
    moods: ["photo", "active"],
    lat: 35.6562,
    lng: 139.7027,
    stayMinutes: 25,
    priceLevel: 0,
    description: "ガード下に広がるウォールアートが連なる通り。",
  },
  {
    id: "spot-12",
    name: "恵比寿ビール小径",
    category: "バー",
    moods: ["gourmet", "mattari"],
    lat: 35.6469,
    lng: 139.7103,
    stayMinutes: 45,
    priceLevel: 2,
    description: "クラフトビールの飲み比べができる小路のバー。",
  },
];
